
version: 2

models:
    - name: my_first_dbt_model
      description: "This is a test comment"
      columns:
          - name: id
            tags: 
             -  pii
            description: "The primary key"
            tests:
                - unique
                - not_null
                
    - name: customers
      description: "customer table"
      columns:
          - name: customer_id
            description: "customer info"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
